events {}

http {
  upstream user_service {
    server user-service:3000;
  }

  upstream product_service {
    server product-service:8000;
  }

  server {
    listen 80;

    location /users {
      proxy_pass http://user_service;
      proxy_set_header Host $host;
    }

    location /products {
      proxy_pass http://product_service;
      proxy_set_header Host $host;
    }

    location /health {
      return 200 'gateway ok\n';
      add_header Content-Type text/plain;
    }
  }
}
